In [8]:
import pandas
import pandas as pd

In [9]:
fd_2010 = pd.read_csv('Clean_Data/FD_2010_CLEAN.csv', encoding='utf-8')
dg_2010 = pd.read_csv('Clean_Data/D_G_2010_CLEAN.csv', encoding='utf-8')

In [10]:
print(len(fd_2010))
fd_2010.head()

3140

   GeoID  Pop_2010  FD_num_2010  FD_pct_2010
0   1001     54571        18428        33.77
1   1003    182265        35211        19.32
2   1005     27457         5722        20.84
3   1007     22915         1045         4.56
4   1009     57322         1548         2.70

In [11]:
print(len(dg_2010))
dg_2010.head()

1026

   GeoID  Year  D_Etab  D_Emp  D_Pay  G_Etab  G_Emp  G_Pay
0   1003  2010      37    271   5046      25   1190  25820
1   1015  2010      30    207   3464      24    734  12338
2   1017  2010       9     66    983       8    200   3634
3   1019  2010       9     43    755       4    114   1612
4   1025  2010      15    158   2467       7    252   4142

In [13]:
merged_10 = pd.merge(dg_2010, fd_2010, on='GeoID')

In [14]:
merged_10.dtypes

GeoID            int64
Year             int64
D_Etab           int64
D_Emp            int64
D_Pay            int64
G_Etab           int64
G_Emp            int64
G_Pay            int64
Pop_2010         int64
FD_num_2010      int64
FD_pct_2010    float64
dtype: object

In [16]:
merged_10.to_csv("ML_Input/ML_2010_CLEAN.csv", index=False, header=True)

In [18]:
check = pd.read_csv('ML_Input/ML_2010_CLEAN.csv', encoding='utf-8')
print(len(check))
check

1025

,GeoID,Year,D_Etab,D_Emp,D_Pay,G_Etab,G_Emp,G_Pay,Pop_2010,FD_num_2010,FD_pct_2010
0,1003,2010,37,271,5046,25,1190,25820,182265,35211,19.32
1,1015,2010,30,207,3464,24,734,12338,118572,30901,26.06
2,1017,2010,9,66,983,8,200,3634,34215,6748,19.72
3,1019,2010,9,43,755,4,114,1612,25989,79,0.31
4,1025,2010,15,158,2467,7,252,4142,25833,5061,19.59
5,1039,2010,13,83,1428,9,284,5022,37765,3334,8.83
6,1045,2010,10,55,963,7,152,2544,50251,13847,27.56
7,1047,2010,12,107,1383,11,250,4935,43820,7786,17.77
8,1051,2010,14,105,1509,8,363,6083,79303,15012,18.93
9,1053,2010,14,154,2261,6,255,4310,38319,5189,13.54
10,1055,2010,25,205,3489,19,522,9510,104430,24779,23.73
11,1057,2010,6,39,654,7,100,1538,17241,438,2.54
12,1063,2010,4,38,479,3,55,874,9045,3287,36.34
13,1071,2010,12,79,1229,13,249,3856,53227,4855,9.12
14,1073,2010,98,965,14728,105,4835,93295,658466,209261,31.78
15,1089,2010,54,427,7659,35,2126,44675,334811,110052,32.87
16,1091,2010,7,43,906,4,109,2240,21027,5587,26.57
17,1093,2010,10,42,767,4,85,1280,30776,538,1.75
18,1095,2010,22,170,2593,20,580,8163,93019,12814,13.78
19,1097,2010,97,849,13932,58,2410,44913,412992,112774,27.31
20,1099,2010,10,59,1181,6,159,2200,23068,7149,30.99
21,1101,2010,36,369,5621,33,1441,28812,229363,64260,28.02
22,1103,2010,27,202,3090,20,634,12716,119490,14010,11.72
23,1107,2010,10,85,1259,4,142,1960,19746,851,4.31
24,1109,2010,5,41,709,8,255,4358,32899,3733,11.35
25,1111,2010,6,43,644,4,113,1943,22913,1061,4.63
26,1113,2010,15,139,2121,8,369,6074,52947,8512,16.08
27,1117,2010,24,204,3864,26,1403,29517,195085,52014,26.66
28,1121,2010,24,181,2626,10,341,6425,82291,12352,15.01
29,1123,2010,12,104,1460,6,239,4707,41616,4598,11.05
...,...,...,...,...,...,...,...,...,...,...,...
995,54081,2010,20,185,3014,15,508,10351,78859,25057,31.78
996,54097,2010,5,33,546,5,159,3175,24254,961,3.96
997,54099,2010,5,34,531,6,98,1415,42481,5924,13.95
998,54103,2010,7,41,648,6,141,2380,16583,7203,43.44
999,55005,2010,10,212,4070,8,298,4947,45870,3811,8.31
1000,55025,2010,24,403,6995,77,4623,84997,488073,110749,22.69
1001,55035,2010,8,77,960,15,965,13653,98736,26549,26.89
1002,55039,2010,12,195,4056,14,823,14560,101633,14228,14.00
1003,55043,2010,10,197,3141,12,302,4581,51208,6565,12.82
1004,55045,2010,7,104,1892,7,267,4766,36842,5301,14.39
1005,55055,2010,7,28,671,15,685,9930,83686,7620,9.11
1006,55059,2010,10,93,1435,26,1197,27491,166426,46129,27.72
1007,55069,2010,6,37,561,5,414,5761,28743,4904,17.06
1008,55073,2010,16,276,5440,28,1085,17541,134063,27814,20.75
1009,55075,2010,6,30,450,11,559,7526,41749,7521,18.01
1010,55079,2010,62,774,12947,203,6912,144515,947735,124078,13.09
1011,55085,2010,5,27,447,6,404,5964,35998,4305,11.96
1012,55093,2010,3,42,789,7,306,4886,41019,5318,12.96
1013,55095,2010,8,44,652,12,377,5962,44205,983,2.22
1014,55099,2010,7,75,1074,4,177,2997,14159,1638,11.57
1015,55101,2010,13,218,3434,36,895,16755,195408,57826,29.59
1016,55105,2010,17,301,5174,24,982,21369,160331,49550,30.90
1017,55111,2010,10,226,4312,13,529,8156,61976,3246,5.24
1018,55115,2010,6,31,419,6,171,2921,41949,6489,15.47
1019,55135,2010,10,214,4635,9,514,8042,52410,8031,15.32
1020,55137,2010,5,49,958,8,180,2906,24496,309,1.26
1021,56007,2010,5,46,954,5,123,4082,15885,8596,54.11
1022,56013,2010,6,60,1361,10,494,7705,40123,6165,15.37
1023,56021,2010,5,55,825,10,470,11108,91738,22102,24.09
1024,56025,2010,9,84,1496,11,409,9847,75450,32267,42.77